### ISSUE TITLE
Project is being sunset

### ISSUE THREAD

**Issue by vreynolds** [honeycombio/influx2hny#10]
See [OSS lifecycle and practices](https://github.com/honeycombio/home/blob/main/honeycomb-oss-lifecycle-and-practices.md)

This project has outlived its useful lifespan, and will be archived in the future. We recommend using the [influxdb receiver](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/influxdbreceiver) with OpenTelemetry to send InfluxDB metrics to Honeycomb.

If you are actively using `influx2hny`, please comment on this issue with your use case.

**Comment by cartermp** [comment]
We moved this back into maintenance for now since the alternatives just aren't quite good enough for users just yet. Over time, it will likely be replaced by OTel metrics.
